const STORAGE_KEY = 'truefix.language';
const SUPPORTED_LANGUAGES = ['zh-CN', 'ja', 'ko', 'en'];
const LANGUAGE_NAMES = { 'zh-CN': '简体中文', ja: '日本語', ko: '한국어', en: 'English' };

const shell = {
  en:{skip:'Skip to content',menu:'Open navigation',language:'Language',home:'Home',about:'About us',support:'Support',feedback:'Feedback',guide:'User guide',eyebrow:'PRODUCT DESIGN PERSPECTIVE',questionLabel:'The question this perspective asks',focusLabel:'What it checks',back:'Back to About us',read:'Read the user guide'},
  'zh-CN':{skip:'跳到正文',menu:'打开导航',language:'语言',home:'首页',about:'关于我们',support:'技术支持',feedback:'反馈交流',guide:'使用指南',eyebrow:'产品设计视角',questionLabel:'这个视角持续追问的问题',focusLabel:'重点检查什么',back:'返回关于我们',read:'阅读使用指南'},
  ja:{skip:'本文へ移動',menu:'ナビゲーションを開く',language:'言語',home:'ホーム',about:'私たちについて',support:'サポート',feedback:'フィードバック',guide:'利用ガイド',eyebrow:'製品設計の視点',questionLabel:'この視点から問い続けること',focusLabel:'確認するポイント',back:'私たちについてへ戻る',read:'利用ガイドを読む'},
  ko:{skip:'본문으로 건너뛰기',menu:'탐색 메뉴 열기',language:'언어',home:'홈',about:'소개',support:'기술 지원',feedback:'피드백',guide:'사용 가이드',eyebrow:'제품 설계 관점',questionLabel:'이 관점이 계속 묻는 질문',focusLabel:'확인하는 항목',back:'소개로 돌아가기',read:'사용 가이드 읽기'}
};

const profiles = {
  'elias-navarro': {
    name:'Elias Navarro', image:'../../assets/team/elias-navarro.jpg',
    en:{role:'Market Infrastructure',question:'Is this the right market product, sent to the right service?',explanation:'This perspective checks the identity and route behind an action. A familiar ticker can mean different instruments on different venues, so TrueFix should show the provider, market, account, and route before anything is sent.',focus:[['Instrument identity','Symbol, venue, currency, and contract details agree.'],['Routing evidence','The selected provider and account are visible before action.'],['Outcome matching','Submitted orders and provider results can be compared.']]},
    'zh-CN':{role:'市场基础设施',question:'这是正确的交易品种吗？操作会发给正确的服务吗？',explanation:'这个视角检查操作背后的标的身份和发送路线。同一个代码在不同市场可能代表不同品种，因此 TrueFix 应在发送前明确显示 Provider、市场、账户和路线。',focus:[['标的身份','核对代码、市场、币种和合约信息。'],['路由依据','操作前显示所选 Provider 与账户。'],['结果核对','可以对照已提交订单与 Provider 返回结果。']]},
    ja:{role:'市場インフラ',question:'正しい商品を、正しいサービスへ送ろうとしているか？',explanation:'この視点は、操作の対象と送信経路を確認します。同じティッカーでも市場によって商品が異なるため、送信前にProvider、市場、口座、経路を表示する必要があります。',focus:[['商品の識別','銘柄、取引所、通貨、契約情報を照合。'],['経路の根拠','選択したProviderと口座を操作前に表示。'],['結果の照合','注文とProviderの応答を比較可能にする。']]},
    ko:{role:'시장 인프라',question:'올바른 상품을 올바른 서비스로 보내고 있는가?',explanation:'이 관점은 작업의 상품 정체성과 전송 경로를 확인합니다. 같은 티커도 시장에 따라 다른 상품일 수 있으므로 전송 전에 Provider, 시장, 계정과 경로를 보여 줘야 합니다.',focus:[['상품 식별','종목, 거래소, 통화와 계약 정보를 대조합니다.'],['경로 근거','선택한 Provider와 계정을 작업 전에 표시합니다.'],['결과 대조','주문과 Provider 응답을 비교할 수 있게 합니다.']]}
  },
  'chen-wei': {
    name:'Chen Wei', image:'../../assets/team/chen-wei.jpg',
    en:{role:'Data Integrity',question:'Can a user tell where this number came from and whether it is current?',explanation:'This perspective keeps market data understandable. TrueFix should preserve the provider, timestamp, currency, adjustment method, and revision history instead of presenting every number as equally reliable.',focus:[['Source','Show which provider supplied the value.'],['Freshness','Make timestamps and stale data visible.'],['Revisions','Keep corrections and transformations explainable.']]},
    'zh-CN':{role:'数据完整性',question:'用户能知道这个数字来自哪里、现在是否仍有效吗？',explanation:'这个视角让行情数据保持可理解。TrueFix 不应把所有数字当成同等可靠，而应保留 Provider、时间、币种、复权方式和修订记录。',focus:[['来源','显示数值由哪个 Provider 提供。'],['时效','明确时间戳和过期数据。'],['修订','让更正和转换过程可以解释。']]},
    ja:{role:'データ完全性',question:'この数値の出所と鮮度を利用者が確認できるか？',explanation:'この視点は市場データを理解可能に保ちます。すべての数値を同等に扱わず、Provider、時刻、通貨、調整方法、改訂履歴を残します。',focus:[['情報源','値を提供したProviderを表示。'],['鮮度','時刻と古いデータを明示。'],['改訂','訂正と変換を説明可能にする。']]},
    ko:{role:'데이터 무결성',question:'이 숫자의 출처와 최신 여부를 사용자가 알 수 있는가?',explanation:'이 관점은 시장 데이터를 이해할 수 있게 유지합니다. 모든 숫자를 똑같이 믿게 하지 않고 Provider, 시간, 통화, 조정 방식과 수정 기록을 남깁니다.',focus:[['출처','값을 제공한 Provider를 표시합니다.'],['최신성','시간과 오래된 데이터를 명확히 합니다.'],['수정','정정과 변환 과정을 설명할 수 있게 합니다.']]}
  },
  'park-min-seo': {
    name:'Park Min-seo', image:'../../assets/team/park-min-seo.jpg',
    en:{role:'Runtime Reliability',question:'When a connection fails, what will the user see and what happens next?',explanation:'Connected services fail, slow down, and reconnect. This perspective asks TrueFix to show the real state, avoid silent retries that change outcomes, and recover without duplicating an action.',focus:[['Visible status','Connected, delayed, retrying, and failed mean different things.'],['Bounded retry','Retries stop and remain visible.'],['Safe recovery','Recovery avoids duplicate orders or hidden state changes.']]},
    'zh-CN':{role:'运行时可靠性',question:'连接失败时，用户会看到什么？接下来会发生什么？',explanation:'外部服务会失败、变慢和重新连接。这个视角要求 TrueFix 显示真实状态，避免可能改变结果的静默重试，并在恢复时防止重复操作。',focus:[['状态可见','连接、延迟、重试和失败需要明确区分。'],['有限重试','重试会停止，而且过程可见。'],['安全恢复','避免重复下单或隐藏的状态变化。']]},
    ja:{role:'ランタイム信頼性',question:'接続失敗時に何が表示され、その後どうなるか？',explanation:'外部サービスは停止、遅延、再接続します。実際の状態を表示し、結果を変える無言の再試行を避け、操作を重複させずに復旧する視点です。',focus:[['状態の表示','接続、遅延、再試行、失敗を区別。'],['有限の再試行','再試行は停止し、経過を表示。'],['安全な復旧','重複注文や隠れた状態変更を防ぐ。']]},
    ko:{role:'런타임 신뢰성',question:'연결이 실패하면 사용자는 무엇을 보고 다음에 무슨 일이 생기는가?',explanation:'외부 서비스는 실패하거나 느려지고 다시 연결됩니다. 실제 상태를 표시하고 결과를 바꿀 수 있는 조용한 재시도를 피하며 작업 중복 없이 복구해야 합니다.',focus:[['상태 표시','연결, 지연, 재시도와 실패를 구분합니다.'],['제한된 재시도','재시도는 멈추며 과정이 보입니다.'],['안전한 복구','중복 주문과 숨은 상태 변경을 막습니다.']]}
  },
  'amara-okafor': {
    name:'Amara Okafor', image:'../../assets/team/amara-okafor.jpg?v=2',
    en:{role:'Systems Architecture',question:'Can one connected service fail without taking down the rest of the app?',explanation:'This perspective separates providers and responsibilities. A broken connector should be isolated, its permissions should stay narrow, and the rest of the workspace should remain useful.',focus:[['Isolation','One provider failure stays inside its boundary.'],['Narrow access','Each connector gets only the access it needs.'],['Predictable recovery','Restarting one part does not reset everything.']]},
    'zh-CN':{role:'系统架构',question:'一个外部服务出问题时，应用其他部分还能继续工作吗？',explanation:'这个视角把 Provider 和职责分开。失效的连接器应该被隔离，权限范围应该保持最小，工作区的其他部分仍然可用。',focus:[['故障隔离','一个 Provider 的故障停留在自身边界内。'],['最小访问','每个连接器只获得必要权限。'],['可预测恢复','重启一个部分不会重置全部。']]},
    ja:{role:'システムアーキテクチャ',question:'一つの接続先が壊れても、他の部分は使い続けられるか？',explanation:'この視点はProviderと責任を分離します。壊れたコネクターを隔離し、権限を狭く保ち、他の作業を継続できるようにします。',focus:[['障害分離','一つのProviderの障害を境界内に留める。'],['限定アクセス','必要な権限だけを接続に与える。'],['予測可能な復旧','一部の再起動で全体をリセットしない。']]},
    ko:{role:'시스템 아키텍처',question:'한 연결 서비스가 실패해도 앱의 나머지는 계속 작동하는가?',explanation:'이 관점은 Provider와 책임을 분리합니다. 고장 난 커넥터를 격리하고 권한을 좁게 유지하며 나머지 작업 공간은 계속 사용할 수 있어야 합니다.',focus:[['장애 격리','한 Provider의 장애를 경계 안에 둡니다.'],['좁은 접근','각 연결에 필요한 권한만 줍니다.'],['예측 가능한 복구','일부 재시작이 전체를 초기화하지 않습니다.']]}
  },
  'sora-kimura': {
    name:'Sora Kimura', image:'../../assets/team/sora-kimura.jpg',
    en:{role:'Human Factors & Risk',question:'Are permission, uncertainty, and risk clear before a person acts?',explanation:'This perspective checks what the interface communicates at the moment of decision. Users should see what is known, what is uncertain, which account is affected, and whether an action can be undone.',focus:[['Plain choices','Controls describe consequences, not internal jargon.'],['Risk before action','Account, size, cost, and risk appear before approval.'],['Clear status','A proposal is never mistaken for a completed trade.']]},
    'zh-CN':{role:'人因与风险',question:'用户行动前，权限、不确定性和风险是否足够清楚？',explanation:'这个视角检查界面在决策时传达了什么。用户应能看见哪些信息确定、哪些不确定、哪个账户会受影响，以及操作能否撤销。',focus:[['选择易懂','控件说明后果，而不是内部术语。'],['风险前置','批准前显示账户、数量、费用和风险。'],['状态清楚','建议方案绝不能看起来像已经成交。']]},
    ja:{role:'ヒューマンファクターとリスク',question:'行動前に権限、不確実性、リスクが明確か？',explanation:'この視点は、判断時に画面が伝える内容を確認します。確かな情報、不確かな情報、影響する口座、取り消し可能性を表示します。',focus:[['分かる選択肢','内部用語ではなく結果を説明。'],['事前のリスク','承認前に口座、数量、費用、リスクを表示。'],['明確な状態','提案を完了済み取引に見せない。']]},
    ko:{role:'인간 요소와 리스크',question:'행동 전에 권한, 불확실성과 리스크가 분명한가?',explanation:'이 관점은 결정 순간에 화면이 무엇을 전달하는지 확인합니다. 확실한 정보와 불확실한 정보, 영향을 받는 계정, 취소 가능 여부를 보여 줍니다.',focus:[['쉬운 선택','내부 용어가 아니라 결과를 설명합니다.'],['행동 전 리스크','승인 전에 계정, 수량, 비용과 리스크를 표시합니다.'],['명확한 상태','제안이 완료된 거래처럼 보이지 않게 합니다.']]}
  },
  'leila-haddad': {
    name:'Leila Haddad', image:'../../assets/team/leila-haddad.jpg',
    en:{role:'AI & Quant Safety',question:'Do AI and automated strategies stay inside the limits the user chose?',explanation:'This perspective treats AI and strategies as limited tools. Their data, actions, accounts, budgets, and risk limits should be explicit, testable, and reviewable after a run.',focus:[['Allowed tools','The agent can call only approved tools.'],['Test before live','Strategies run in backtest or simulation first.'],['Reviewable record','Inputs, decisions, actions, and limits are logged.']]},
    'zh-CN':{role:'AI 与量化安全',question:'AI 和自动策略是否始终处于用户选择的限制内？',explanation:'这个视角把 AI 和策略当作权限有限的工具。它们使用的数据、操作、账户、预算和风险限制都应该明确、可测试，并且运行后可以检查。',focus:[['允许的工具','Agent 只能调用已经批准的工具。'],['先测试再实盘','策略先在回测或模拟环境运行。'],['可审查记录','记录输入、判断、操作和限制。']]},
    ja:{role:'AIとクオンツの安全性',question:'AIと自動戦略は利用者が選んだ制限内に留まるか？',explanation:'この視点はAIと戦略を制限付きの道具として扱います。データ、操作、口座、予算、リスク制限を明示し、テストと事後確認を可能にします。',focus:[['許可したツール','Agentは承認済みツールだけを使用。'],['実運用前のテスト','バックテストやシミュレーションを先に実行。'],['確認可能な記録','入力、判断、操作、制限を記録。']]},
    ko:{role:'AI와 퀀트 안전',question:'AI와 자동 전략이 사용자가 정한 제한 안에 머무르는가?',explanation:'이 관점은 AI와 전략을 제한된 도구로 봅니다. 데이터, 작업, 계정, 예산과 리스크 제한을 명확히 하고 테스트와 사후 검토가 가능해야 합니다.',focus:[['허용 도구','Agent는 승인된 도구만 호출합니다.'],['실거래 전 테스트','백테스트나 시뮬레이션을 먼저 실행합니다.'],['검토 가능한 기록','입력, 판단, 작업과 제한을 기록합니다.']]}
  }
};

function normalizeLanguage(value){const v=String(value||'').toLowerCase();if(v.startsWith('zh'))return'zh-CN';if(v.startsWith('ja'))return'ja';if(v.startsWith('ko'))return'ko';if(v.startsWith('en'))return'en';return null}
function detectLanguage(){const path=window.TrueFixLocale?.pathLanguage();if(path)return path;try{const saved=localStorage.getItem(STORAGE_KEY);if(SUPPORTED_LANGUAGES.includes(saved))return saved}catch{}for(const value of navigator.languages||[navigator.language]){const locale=normalizeLanguage(value);if(locale)return locale}return'en'}
const id=document.body.dataset.person;
const profile=profiles[id]||profiles['elias-navarro'];
function applyLanguage(locale){const lang=SUPPORTED_LANGUAGES.includes(locale)?locale:'en';const common=shell[lang];const content=profile[lang];document.documentElement.lang=lang;document.title=`${profile.name} — TrueFix Studio`;document.querySelectorAll('[data-shell]').forEach(node=>{const value=common[node.dataset.shell];if(value)node.textContent=value});document.querySelector('[data-name]').textContent=profile.name;document.querySelector('[data-role]').textContent=content.role;document.querySelector('[data-question]').textContent=content.question;document.querySelector('[data-explanation]').textContent=content.explanation;document.querySelector('[data-portrait]').src=profile.image;document.querySelector('[data-portrait]').alt=`${profile.name} portrait`;document.querySelector('[data-focus]').innerHTML=content.focus.map(([title,text])=>`<div><strong>${title}</strong><span>${text}</span></div>`).join('');const current=document.querySelector('[data-language-current]');if(current)current.textContent=LANGUAGE_NAMES[lang];const toggle=document.querySelector('[data-language-toggle]');if(toggle)toggle.setAttribute('aria-label',`${common.language}: ${LANGUAGE_NAMES[lang]}`);document.querySelectorAll('[data-language]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.language===lang)));window.TrueFixLocale?.activate(lang)}
const menuButton=document.querySelector('[data-menu-button]');const nav=document.querySelector('[data-nav]');const picker=document.querySelector('[data-language-picker]');const toggle=document.querySelector('[data-language-toggle]');const menu=document.querySelector('[data-language-menu]');const options=[...document.querySelectorAll('[data-language]')];
function setMenu(open){menuButton.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);if(!open)setLanguages(false)}function setLanguages(open,focus=false){picker.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-hidden',String(!open));menu.inert=!open;options.forEach(option=>option.tabIndex=open&&option.getAttribute('aria-selected')==='true'?0:-1);if(open&&focus)(options.find(option=>option.tabIndex===0)||options[0])?.focus()}
menuButton.addEventListener('click',()=>setMenu(menuButton.getAttribute('aria-expanded')!=='true'));nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>setMenu(false)));toggle.addEventListener('click',()=>setLanguages(toggle.getAttribute('aria-expanded')!=='true',true));options.forEach((button,index)=>{button.addEventListener('click',()=>window.TrueFixLocale?window.TrueFixLocale.navigate(button.dataset.language):applyLanguage(button.dataset.language));button.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(event.key))return;event.preventDefault();let next=index;if(event.key==='ArrowDown')next=(index+1)%options.length;if(event.key==='ArrowUp')next=(index-1+options.length)%options.length;if(event.key==='Home')next=0;if(event.key==='End')next=options.length-1;options[next].tabIndex=0;options[next].focus()})});document.addEventListener('click',event=>{if(!picker.contains(event.target))setLanguages(false)});document.addEventListener('keydown',event=>{if(event.key==='Escape'){setLanguages(false);setMenu(false);menuButton.focus()}});applyLanguage(detectLanguage());
